name: Snyk Dependency Scan

on: [push, pull_request]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk Security Scan
        run: snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
